name: BestPractices
# In a production application the Team ID would be set here.
# settings:
#  DEVELOPMENT_TEAM: "XXX"
options:
  bundleIdPrefix: com.bestpractices
  deploymentTarget:
    iOS: "12.0"
targets:
  BestPractices:
    type: application
    platform: iOS
    sources: BestPractices
    dependencies:
      - target: Core
      - carthage: ReactiveCocoa
      - carthage: ReactiveSwift
      - carthage: Result
    scheme:
      testTargets:
        - BestPracticesTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  BestPracticesTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/BestPractices.app/BestPractices"
    sources: Tests/BestPracticesTests/
    dependencies:
      - target: BestPractices
      - carthage: Quick
      - carthage: Nimble
  Core:
    type: framework
    platform: iOS
    sources:
      - Core
    dependencies:
      - carthage: ReactiveSwift
      - carthage: Result
    scheme:
      testTargets: 
        - CoreTests
      gatherCoverageData: true
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  CoreTests:
    platform: iOS
    type: bundle.unit-test
    sources: Tests/CoreTests/
    dependencies:
      - target: Core
      - carthage: Quick
      - carthage: Nimble
