name: BestPractices
configFiles:
  Debug: Configurations/Debug.xcconfig
  Release: Configurations/Release.xcconfig
options:
  bundleIdPrefix: com.westinnewell
  deploymentTarget:
    iOS: "12.0"
targets:
  BestPractices:
    type: application
    platform: iOS
    sources: 
      - BestPractices
    settings:
      CUSTOM_BUILD_SETTING: my_value
    dependencies:
      - target: Core
      - carthage: ReactiveCocoa
      - carthage: ReactiveSwift
      - carthage: Result
    configFiles:
      Debug: Configurations/BestPracticesDebug.xcconfig
      Release: Configurations/BestPracticesRelease.xcconfig
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
  Core:
    type: framework
    platform: iOS
    sources:
      - Core
    dependencies:
      - carthage: ReactiveSwift
      - carthage: Result
    configFiles:
      Debug: Configurations/MyFrameworkDebug.xcconfig
      Release: Configurations/MyFrameworkRelease.xcconfig
    prebuildScripts:
      - path: Scripts/swiftlint-check.sh
        name: Swift Lint Check
