version: 2
jobs:
  build:

    macos:
      xcode: "10.1.0"
    
    # This should set the approprate ruby version from the .ruby-version file
    shell: /bin/bash --login -eo pipefail

    environment:
      ENV: CI

    steps:
      - checkout

      - run:
          name: Bootstrap Project
          command: make bootstrap

      - run:
          name: Lint
          command: make lint

      - run:
          name: Build and run tests
          command: make test

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
